### ISSUE TITLE
Is the project live?

### ISSUE THREAD

**Issue by Tolsi** [bridgefy/bridgefy-android-samples#13]
The idea, your website, and marketing sounds great, but your application installed on 2 android phones connected by bluetooth (and even wifi to one network) lying nearby cannot transmit a message from one to another.

**Comment by jorgeribs** [comment]
Hi there,

The same code you see on Github is the one we use for our own demo app,
Bridgefy <http://www.bfy.buzz>. This is probably an issue with the
implementation, but don't worry, we can help! Could you please send logs
and all info that you think might help, so that we may identify the error
and fix it?

Thank you,

*Jorge Rios*
CEO
Bridgefy <http://www.bridgefy.me> – Making Apps Work Without Internet

What is Bridgefy? Click here to watch the video.
<http://www.bit.ly/bridgefysdk>

The contents of this message do not represent in any legal or official way
the opinions, decisions or postures of any company whatsoever. Nothing in
this message is intended to constitute an electronic signature unless a
specific statement to the contrary is included in this message.
Reproduction of parts or the entirety of this message is prohibited if not
expressly permitted by the sender.

**Comment by kekoyde** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/bridgefy/bridgefy-android-samples#bridgefy-android-sdk-v-1124).

Thank you!
