### ISSUE TITLE
Error initializing Bridgefy SDK offline when using Product Flavors

### ISSUE THREAD

**Issue by Anees-Iqbal** [bridgefy/bridgefy-android-samples#24]
On Android, if two Product flavors are being used with two separate Bridgefy API keys, how can one initialize the Bridgefy with  with certificate as there is always one BuildConfig file generated under the same Package when where as the each Flavor has its uniques Application ID?
```
W/System.err:     at com.bridgefy.sdk.framework.utils.Utils.getBuildConfigValue(SourceFile:197)
W/System.err:     at com.bridgefy.sdk.client.registration.Registration.loadCertificate(SourceFile:223)
W/System.err:     at com.bridgefy.sdk.client.Bridgefy.initialize(SourceFile:148)
W/System.err:     at com.bridgefy.sdk.client.Bridgefy.initialize(SourceFile:115)  
```
Bridgefy SDK seems to load the certificate using the apllication ID from BuildConfig generated file under the package name  same as Application ID whereas it is not unable to get a buildconfig under a dynamic package name as ApplicationID when using Product Flavors. Please also update for new stable release of the Bridgefy SDK.  I am currently using Bridgefy SDK Version 1.1.26

**Comment by kekoyde** [comment]
Bridgefy can be [initialized offline](https://github.com/bridgefy/bridgefy-android-samples#initialize-bridgefy-without-an-internet-connection), by [downloading a temporary license](https://admin.bridgefy.me/license), a text file containing the bridgefy license, you can preload this file in your app and bridgefy will start the offline SDK, in order to preload the license, you must follow these steps:

1. Go to the [Bridgefy site](https://admin.bridgefy.me/) and download the file
2. Rename the file by your **application package** or **applicationId** - Bridgefy will try to find the file in the **assets** folder, with the **applicationId**, if it does not exist, it will try to find it with **package name**
3. The license is valid for **30 days**, after creating the license in the dashboard
