### ISSUE TITLE
MessageSent content is null

### ISSUE THREAD

**Issue by antonkazakov** [bridgefy/bridgefy-android-samples#4]
Why content of message argument in in onMessageSent callback is always null? Is it conceived by API design?

**Comment by dekaru** [comment]
Hi @antonkazakov, thank you for this report! We can confirm we are seeing this as well and it happens under specific circumstances. We are looking to fixing this into the expected behavior and we'll get back to you shortly.

**Comment by kekoyde** [comment]
Hi @antonkazakov , 
Bridgefy only uses the content of the message through a process that guarantees security and sending it to the devices, this process is irreversible, so we notify the UUID of the message without content on MessageListener.onMessageSent (Message).

We suggest that customers manage the messages sent by Bridgefy.
The Bridgefy.sendMessage () returns a string representation of the UUID used to identify this Message throughout the Bridgefy framework.
Same UUID of the Message returned in MessageListener.onMessageSent (Message)

We will be updating the MessageListener.onMessageSent method so that it returns only the Message's UUID in a String representation and mark the current method as deprecated. 
We'll let you know once that method is updated.

**Comment by antonkazakov** [comment]
Thank you

**Comment by dustedrob** [comment]
Sorry for the late reply. In version 1.1.11 the onMessageSent(Message) was deprecated in favor of onMessageSent(String).
